import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.css'
import Nav from "../components/Nav"
import Hero from "../components/Hero"
import Body from "../components/Body"
import { Tabprovider } from "../hooks/tabsContext"


import {
  useQuery,
  gql
} from "@apollo/client";



const EXCHANGE_RATES = gql`
  query{
  categories {
    categoryId
    name
    products {
      productId
      name
      price
      discount
      unitsSold
    }
    subCategories{
      name
      subCategoryId
      categoryId
    }
  }
}
`;


export default function Home() {
  const { loading, error, data } = useQuery(EXCHANGE_RATES);
  return (
    <div>
      <Tabprovider>

        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* {console.log(data)} */}
        <Nav />
        <Hero />
        <Body />
      </Tabprovider>
    </div>
  )
}
